name: Simple Working Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install and build
      run: |
        npm ci --production
        npm run build
        
    - name: Deploy to VPS - SIMPLE & FAST
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        timeout: 300s
        script: |
          set -e
          
          echo "🚀 SIMPLE DEPLOYMENT - 3 Steps Only"
          
          # 1. FRONTEND - Complete replacement
          cd /tmp
          rm -rf ks-offerte-chat
          git clone https://github.com/mennovdmm/ks-offerte-chat.git
          cd ks-offerte-chat
          
          npm ci --production
          npm run build
          
          sudo rm -rf /var/www/ai.dehuisraad.com/*
          sudo cp -r build/* /var/www/ai.dehuisraad.com/
          sudo chown -R www-data:www-data /var/www/ai.dehuisraad.com
          
          # 2. SERVER - Copy EXACT repo files (not old files)
          cd /root/ks-streaming-api
          cp /tmp/ks-offerte-chat/server/express-server.js ./server.js
          cp /tmp/ks-offerte-chat/server/ecosystem.config.js ./ecosystem.config.js
          
          # 3. RESTART PM2 PROPERLY (fresh start with environment)
          pm2 delete ks-streaming-api || true
          pm2 start ecosystem.config.js
          
          echo "⏳ Waiting for server startup..."
          sleep 3
          
          # 4. VERIFICATION - Fail fast if broken
          echo "🧪 Testing health endpoint..."
          curl -f http://127.0.0.1:3001/api/health || exit 1
          
          echo "🧪 Testing chat endpoint..."
          curl -f -X POST http://127.0.0.1:3001/api/chat \
            -H "Content-Type: application/json" \
            -d '{"message": "deployment test"}' || exit 1
          
          echo "✅ Deployment successful!"
          echo "🌐 Frontend: https://ai.dehuisraad.com"
          echo "💬 API: https://ai.dehuisraad.com/api/chat"