name: Deploy to VPS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build React app
      run: npm run build
      
    - name: Debug secrets
      run: |
        echo "Host: ${{ secrets.VPS_HOST }}"
        echo "User: ${{ secrets.VPS_USER }}"
        echo "Key length: ${#VPS_SSH_KEY}"
      env:
        VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        
    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: 22
        debug: true
        script_stop: false
        script: |
          # Create backup of current site
          sudo mkdir -p /var/www/backup
          if [ -d "/var/www/ai.dehuisraad.com" ]; then
            sudo cp -r /var/www/ai.dehuisraad.com /var/www/backup/ai.dehuisraad.com-$(date +%Y%m%d_%H%M%S)
          fi
          
          # Create web directory if it doesn't exist
          sudo mkdir -p /var/www/ai.dehuisraad.com
          sudo chown -R www-data:www-data /var/www/ai.dehuisraad.com
          
          # Clone/pull latest code
          cd /tmp
          if [ -d "ks-offerte-chat" ]; then
            cd ks-offerte-chat
            git pull origin main
          else
            git clone https://github.com/mennovdmm/ks-offerte-chat.git
            cd ks-offerte-chat
          fi
          
          # Install dependencies and build
          npm ci
          npm run build
          
          # Deploy build to web directory
          sudo rm -rf /var/www/ai.dehuisraad.com/*
          sudo cp -r build/* /var/www/ai.dehuisraad.com/
          sudo chown -R www-data:www-data /var/www/ai.dehuisraad.com
          
          # Ensure nginx proxy configuration exists
          echo "🔧 Checking nginx proxy configuration..."
          if ! grep -q "location /api/" /etc/nginx/sites-available/ai.dehuisraad.com 2>/dev/null; then
            echo "⚠️ Adding missing nginx proxy configuration"
            sudo tee -a /etc/nginx/sites-available/ai.dehuisraad.com << 'EOF'

    # API Proxy to VPS streaming server
    location /api/ {
        proxy_pass http://localhost:3001/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_connect_timeout 300s;
        proxy_send_timeout 300s;
        proxy_read_timeout 300s;
        send_timeout 300s;
    }
EOF
            sudo nginx -t && sudo systemctl reload nginx
          else
            echo "✅ Nginx proxy configuration already exists"
          fi
          
          # Deploy VPS Express server
          echo "🚀 Deploying VPS Express server..."
          chmod +x /tmp/ks-offerte-chat/deploy-to-vps.sh
          
          # Set environment variables for deployment script
          export LANGFLOW_API_URL="${{ secrets.LANGFLOW_API_URL }}"
          export LANGFLOW_API_KEY="${{ secrets.LANGFLOW_API_KEY }}"
          
          # Run deployment script
          /tmp/ks-offerte-chat/deploy-to-vps.sh
          
          # Test deployment with retries
          for i in {1..5}; do
            echo "Health check attempt $i/5..."
            if curl -f https://ai.dehuisraad.com/api/health; then
              echo "✅ Health check passed!"
              break
            else
              echo "❌ Health check failed, waiting..."
              if [ $i -eq 5 ]; then
                echo "❌ All health checks failed"
                exit 1
              fi
              sleep 5
            fi
          done
          
          echo "🚀 Deployment successful!"
    
    - name: Send deployment notification
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Deployment successful to https://ai.dehuisraad.com"
        else
          echo "❌ Deployment failed!"
          exit 1
        fi